// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID    uuid.UUID
	Email string
}

type WebauthnCredential struct {
	ID              []byte
	UserID          uuid.UUID
	PublicKey       []byte
	AttestationType pgtype.Text
	Aaguid          []byte
	SignCount       pgtype.Int8
	Transports      []string
}
