// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID                 uuid.UUID
	CreatedAt          time.Time
	LastUsedAt         pgtype.Timestamptz
	CreatedAtIp        string
	CreatedAtUserAgent pgtype.Text
	DeviceNickname     pgtype.Text
	Token              string
	UserID             uuid.UUID
	ExpiresAt          pgtype.Timestamptz
	IsLong             bool
}

type User struct {
	ID          uuid.UUID
	Name        pgtype.Text
	DisplayName pgtype.Text
}

type WebauthnCredential struct {
	ID                 []byte
	UserID             uuid.UUID
	Nickname           pgtype.Text
	PublicKey          []byte
	AttestationType    pgtype.Text
	Aaguid             uuid.UUID
	SignCount          int64
	Transports         []string
	UserPresentFlag    bool
	UserVerifiedFlag   bool
	BackupEligibleFlag bool
	BackupStateFlag    bool
	CloneWarning       bool
	CreatedAt          time.Time
	LastUsedAt         pgtype.Timestamptz
}
