// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          uuid.UUID
	Name        pgtype.Text
	DisplayName pgtype.Text
}

type WebauthnCredential struct {
	ID                 []byte
	UserID             uuid.UUID
	Nickname           pgtype.Text
	PublicKey          []byte
	AttestationType    pgtype.Text
	Aaguid             []byte
	SignCount          int64
	Transports         []string
	UserPresentFlag    bool
	UserVerifiedFlag   bool
	BackupEligibleFlag bool
	BackupStateFlag    bool
	CloneWarning       bool
	CreatedAt          time.Time
	LastUsedAt         pgtype.Timestamptz
}
