// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO webauthn_credentials (id, user_id, public_key, attestation_type, aaguid, sign_count, transports)
VALUES ($1::bytea, $2::uuid, $3::bytea, $4::text, $5::bytea, $6::bigint, $7::text[])
`

type CreateCredentialParams struct {
	ID              []byte
	UserID          uuid.UUID
	PublicKey       []byte
	AttestationType string
	Aaguid          []byte
	SignCount       int64
	Transports      []string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Aaguid,
		arg.SignCount,
		arg.Transports,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email) VALUES ($1::uuid, $2::text)
`

type CreateUserParams struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Email)
	return err
}

const isEmailExists = `-- name: IsEmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1::text)
`

func (q *Queries) IsEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCredentialsByUser = `-- name: ListCredentialsByUser :many
SELECT id, user_id, public_key, attestation_type, aaguid, sign_count, transports
FROM webauthn_credentials
WHERE user_id = $1::uuid
`

func (q *Queries) ListCredentialsByUser(ctx context.Context, userID uuid.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.Transports,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
