// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO webauthn_credentials (id, user_id, nickname, public_key, attestation_type, aaguid, sign_count, transports, user_present_flag, user_verified_flag, backup_eligible_flag, backup_state_flag, clone_warning)
VALUES ($1::bytea, $2::uuid, $3::text, $4::bytea, $5::text, $6::bytea, $7::bigint, $8::text[], $9::boolean, $10::boolean, $11::boolean, $12::boolean, $13::boolean)
`

type CreateCredentialParams struct {
	ID                 []byte
	UserID             uuid.UUID
	Nickname           string
	PublicKey          []byte
	AttestationType    string
	Aaguid             []byte
	SignCount          int64
	Transports         []string
	UserPresentFlag    bool
	UserVerifiedFlag   bool
	BackupEligibleFlag bool
	BackupStateFlag    bool
	CloneWarning       bool
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.Nickname,
		arg.PublicKey,
		arg.AttestationType,
		arg.Aaguid,
		arg.SignCount,
		arg.Transports,
		arg.UserPresentFlag,
		arg.UserVerifiedFlag,
		arg.BackupEligibleFlag,
		arg.BackupStateFlag,
		arg.CloneWarning,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name) VALUES ($1::uuid, $2::text)
`

type CreateUserParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Name)
	return err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM webauthn_credentials
WHERE user_id = $1::uuid AND id = $2::uuid
`

type DeleteCredentialParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteCredential, arg.UserID, arg.ID)
	return err
}

const getUserFromID = `-- name: GetUserFromID :one
SELECT id, name, display_name FROM users WHERE id = $1::uuid
`

func (q *Queries) GetUserFromID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserFromID, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.DisplayName)
	return i, err
}

const isEmailExists = `-- name: IsEmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE name = $1::text)
`

func (q *Queries) IsEmailExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCredentialsForUser = `-- name: ListCredentialsForUser :many
SELECT id, user_id, nickname, public_key, attestation_type, aaguid, sign_count, transports, user_present_flag, user_verified_flag, backup_eligible_flag, backup_state_flag, clone_warning, created_at, last_used_at
FROM webauthn_credentials
WHERE user_id = $1::uuid
`

func (q *Queries) ListCredentialsForUser(ctx context.Context, userID uuid.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listCredentialsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nickname,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.Transports,
			&i.UserPresentFlag,
			&i.UserVerifiedFlag,
			&i.BackupEligibleFlag,
			&i.BackupStateFlag,
			&i.CloneWarning,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSignCountForCredential = `-- name: UpdateSignCountForCredential :exec
UPDATE webauthn_credentials
SET sign_count = $1::bigint, last_used_at = NOW()
WHERE id = $2::bytea
`

type UpdateSignCountForCredentialParams struct {
	SignCount int64
	ID        []byte
}

func (q *Queries) UpdateSignCountForCredential(ctx context.Context, arg UpdateSignCountForCredentialParams) error {
	_, err := q.db.Exec(ctx, updateSignCountForCredential, arg.SignCount, arg.ID)
	return err
}
